# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara'
gem 'down'
gem 'erb_lint'
gem 'fast_ostruct'
gem 'front_matter_parser'
gem 'geo_coord', require: 'geo/coord'
gem 'herb'
gem 'http'
gem 'nokogiri'
gem 'openssl'
gem 'ougai'
gem 'parallel'
gem 'puma'
gem 'rack'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'ruby-limiter'
gem 'selenium-webdriver'
gem 'sqlite3'
gem 'stringex'
gem 'tilt'
gem 'webmock'
